"use strict";

Swal.fire({
  title: "¡Bienvenido a Netflix!",
  text: "¿De que parte del Perú nos visitas?",
  icon: "question",
  input: "select",
  inputPlaceholder: "Departamento",
  inputOptions: {
    lima: "Lima",
    amazonas: "Amazonas",
    ancash: "Áncash",
    apurimac: "Apurímac",
    arequipa: "Arequipa",
    ayacucho: "Ayacucho",
    cajamarca: "Cajamarca",
    callao: "Callao",
    cuzco: "Cuzco",
    huancavelica: "Huancavelica",
    huanuco: "Huánuco",
    ica: "Ica",
    junín: "Junín",
    laLibertad: "La Libertad",
    lambayeque: "Lambayeque",
    loreto: "Loreto",
    madreDeDios: "Madre de Dios",
    moquegua: "Moquegua",
    pasco: "Pasco",
    piura: "Piura",
    puno: "Puno",
    sanMartin: "San Martín",
    tacna: "Tacna",
    tumbes: "Tumbes",
    ucayali: "Ucayali",
  },
});
